name: API key test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  api_key: ${{ secrets.OPENAI_API_KEY }}  # Ensuring the correct environment variable is set

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script with streamlit
        run: streamlit run main.py
